#!/usr/bin/env node
/**
 * ดึงโครงสร้างฐานข้อมูลปัจจุบันจาก Supabase ออกมาเป็นไฟล์ SQL
 *
 * โปรเจกต์นี้ไม่เคยมี schema อยู่ใน version control เลย — โครงสร้างตารางมีอยู่แต่ในฐานข้อมูลจริง
 * สคริปต์นี้ทำหน้าที่ "ถ่ายรูป" โครงสร้างปัจจุบันเก็บไว้ เพื่อให้:
 *   1. มีของอ้างอิงตอนเขียน migration ของระบบใหม่
 *   2. สร้างฐานข้อมูลเปล่าขึ้นมาใหม่ได้ (เครื่อง dev, ฐานทดสอบ)
 *   3. เห็นได้จาก git ว่าโครงสร้างเปลี่ยนอะไรไปบ้าง
 *
 * ใช้ information_schema + pg_catalog แทน pg_dump เพราะไม่ต้องติดตั้ง PostgreSQL client
 *
 * รัน: npm run db:dump-schema
 */
const fs   = require('fs')
const path = require('path')
require('dotenv').config({ quiet: true })

const { pool, getDatabaseInfo } = require('../src/database')

const OUT_DIR  = path.join(__dirname, '..', 'db')
const OUT_FILE = path.join(OUT_DIR, 'schema.sql')

const q = (name) => `"${name}"`

/** ประกอบ type ของคอลัมน์กลับมาเป็นข้อความ เช่น character varying(50) → varchar(50) */
function columnType(col) {
  const t = col.data_type
  if (t === 'character varying') return col.character_maximum_length ? `varchar(${col.character_maximum_length})` : 'varchar'
  if (t === 'character')         return col.character_maximum_length ? `char(${col.character_maximum_length})` : 'char'
  if (t === 'numeric') {
    if (col.numeric_precision == null) return 'numeric'
    return col.numeric_scale ? `numeric(${col.numeric_precision},${col.numeric_scale})` : `numeric(${col.numeric_precision})`
  }
  if (t === 'USER-DEFINED') return col.udt_name
  if (t === 'ARRAY')        return `${col.udt_name.replace(/^_/, '')}[]`
  return t
}

async function fetchTables(client) {
  const { rows } = await client.query(`
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
    ORDER BY table_name`)
  return rows.map((r) => r.table_name)
}

async function fetchColumns(client, table) {
  const { rows } = await client.query(`
    SELECT column_name, data_type, udt_name, character_maximum_length,
           numeric_precision, numeric_scale, is_nullable, column_default, is_identity
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = $1
    ORDER BY ordinal_position`, [table])
  return rows
}

async function fetchConstraints(client, table) {
  // pg_get_constraintdef ให้ข้อความ constraint ที่เอาไปใช้ได้ตรง ๆ ไม่ต้องประกอบเอง
  const { rows } = await client.query(`
    SELECT con.conname, pg_get_constraintdef(con.oid) AS definition, con.contype
    FROM pg_constraint con
    JOIN pg_class rel   ON rel.oid = con.conrelid
    JOIN pg_namespace ns ON ns.oid = rel.relnamespace
    WHERE ns.nspname = 'public' AND rel.relname = $1
    ORDER BY con.contype, con.conname`, [table])
  return rows
}

async function fetchIndexes(client, table) {
  const { rows } = await client.query(`
    SELECT indexname, indexdef
    FROM pg_indexes
    WHERE schemaname = 'public' AND tablename = $1
      -- index ที่เกิดจาก PRIMARY KEY / UNIQUE ถูกสร้างมาพร้อม constraint อยู่แล้ว
      AND indexname NOT IN (
        SELECT con.conname FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        WHERE rel.relname = $1 AND con.contype IN ('p','u')
      )
    ORDER BY indexname`, [table])
  return rows
}

async function fetchViews(client) {
  const { rows } = await client.query(`
    SELECT table_name, view_definition
    FROM information_schema.views
    WHERE table_schema = 'public'
    ORDER BY table_name`)
  return rows
}

async function fetchFunctions(client) {
  const { rows } = await client.query(`
    SELECT p.proname, pg_get_functiondef(p.oid) AS definition
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.prokind = 'f'
    ORDER BY p.proname`)
  return rows
}

async function fetchTriggers(client) {
  const { rows } = await client.query(`
    SELECT tgname, pg_get_triggerdef(t.oid) AS definition
    FROM pg_trigger t
    JOIN pg_class rel    ON rel.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = rel.relnamespace
    WHERE ns.nspname = 'public' AND NOT t.tgisinternal
    ORDER BY tgname`)
  return rows
}

async function fetchEnums(client) {
  const { rows } = await client.query(`
    SELECT t.typname, string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    JOIN pg_enum e       ON e.enumtypid = t.oid
    JOIN pg_namespace n  ON n.oid = t.typnamespace
    WHERE n.nspname = 'public'
    GROUP BY t.typname
    ORDER BY t.typname`)
  return rows
}

function renderTable(table, columns, constraints) {
  const lines = columns.map((col) => {
    let def = `  ${q(col.column_name)} ${columnType(col)}`
    if (col.is_identity === 'YES') def += ' GENERATED BY DEFAULT AS IDENTITY'
    else if (col.column_default !== null) def += ` DEFAULT ${col.column_default}`
    if (col.is_nullable === 'NO') def += ' NOT NULL'
    return def
  })

  // PK/UNIQUE/CHECK เขียนในตัว CREATE TABLE ได้เลย ส่วน FK แยกไปท้ายไฟล์ กันปัญหาลำดับตาราง
  for (const c of constraints.filter((c) => c.contype !== 'f')) {
    lines.push(`  CONSTRAINT ${q(c.conname)} ${c.definition}`)
  }

  return `CREATE TABLE IF NOT EXISTS ${q(table)} (\n${lines.join(',\n')}\n);`
}

async function main() {
  const info = getDatabaseInfo()
  console.log(`กำลังอ่านโครงสร้างจาก ${info.host}:${info.port} (ssl: ${info.ssl})`)

  const client = await pool.connect()
  const out = []
  const stats = { tables: 0, views: 0, functions: 0, triggers: 0, enums: 0, foreignKeys: 0 }

  try {
    out.push('-- FarmStock — โครงสร้างฐานข้อมูล')
    out.push(`-- สร้างอัตโนมัติจาก scripts/dump-schema.js เมื่อ ${new Date().toISOString()}`)
    out.push(`-- ต้นทาง: ${info.host}`)
    out.push('--')
    out.push('-- ไฟล์นี้ generate ขึ้นมา ห้ามแก้มือ — ถ้าจะเปลี่ยนโครงสร้างให้เขียน migration แล้ว dump ใหม่')
    out.push('')

    const enums = await fetchEnums(client)
    if (enums.length) {
      out.push('-- ─────────── ENUM ───────────')
      for (const e of enums) out.push(`CREATE TYPE ${q(e.typname)} AS ENUM (${e.labels});`)
      out.push('')
      stats.enums = enums.length
    }

    const tables = await fetchTables(client)
    const foreignKeys = []

    out.push('-- ─────────── ตาราง ───────────')
    for (const table of tables) {
      const [columns, constraints] = await Promise.all([
        fetchColumns(client, table),
        fetchConstraints(client, table),
      ])
      out.push('')
      out.push(renderTable(table, columns, constraints))

      for (const fk of constraints.filter((c) => c.contype === 'f')) {
        foreignKeys.push(`ALTER TABLE ${q(table)} ADD CONSTRAINT ${q(fk.conname)} ${fk.definition};`)
      }

      const indexes = await fetchIndexes(client, table)
      for (const idx of indexes) out.push(`${idx.indexdef};`)
    }
    stats.tables = tables.length
    stats.foreignKeys = foreignKeys.length

    if (foreignKeys.length) {
      out.push('')
      out.push('-- ─────────── Foreign key ───────────')
      out.push(...foreignKeys)
    }

    const functions = await fetchFunctions(client)
    if (functions.length) {
      out.push('')
      out.push('-- ─────────── ฟังก์ชัน ───────────')
      for (const f of functions) out.push('', `${f.definition};`)
      stats.functions = functions.length
    }

    const views = await fetchViews(client)
    if (views.length) {
      out.push('')
      out.push('-- ─────────── View ───────────')
      for (const v of views) out.push('', `CREATE OR REPLACE VIEW ${q(v.table_name)} AS\n${v.view_definition.trim()}`)
      stats.views = views.length
    }

    const triggers = await fetchTriggers(client)
    if (triggers.length) {
      out.push('')
      out.push('-- ─────────── Trigger ───────────')
      for (const t of triggers) out.push(`${t.definition};`)
      stats.triggers = triggers.length
    }

    fs.mkdirSync(OUT_DIR, { recursive: true })
    fs.writeFileSync(OUT_FILE, out.join('\n') + '\n', 'utf8')

    console.log(`\n✔ เขียนแล้ว: ${path.relative(process.cwd(), OUT_FILE)}`)
    console.log(`  ตาราง ${stats.tables} · foreign key ${stats.foreignKeys} · view ${stats.views} · ฟังก์ชัน ${stats.functions} · trigger ${stats.triggers} · enum ${stats.enums}`)
    console.log(`\n  ตารางที่เจอ: ${tables.join(', ')}`)
  } finally {
    client.release()
    await pool.end()
  }
}

main().catch((err) => {
  console.error('\n❌ ดึงโครงสร้างไม่สำเร็จ:', err.message)
  if (err.code === 'ENOTFOUND') {
    console.error('   host ไม่ resolve — โปรเจกต์ Supabase อาจถูก pause อยู่ ลองเข้า dashboard กด Resume ก่อน')
  }
  process.exit(1)
})
